// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKwBUSeUpSWPTsFQHL3pF5KG30J5--lp0',
    appId: '1:775956968299:web:322252afdea6f57fe6122e',
    messagingSenderId: '775956968299',
    projectId: 'dalel-d73c2',
    authDomain: 'dalel-d73c2.firebaseapp.com',
    storageBucket: 'dalel-d73c2.firebasestorage.app',
    measurementId: 'G-9NYEE1QNNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Nv0DfbwsA6CymraanO3KiP7XJV0XnY0',
    appId: '1:775956968299:android:7b6d98db3212fef1e6122e',
    messagingSenderId: '775956968299',
    projectId: 'dalel-d73c2',
    storageBucket: 'dalel-d73c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCki9qJ-DZwe21MlUdIuB3w7vqan8YUwlQ',
    appId: '1:775956968299:ios:db73c4733004c3a9e6122e',
    messagingSenderId: '775956968299',
    projectId: 'dalel-d73c2',
    storageBucket: 'dalel-d73c2.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCki9qJ-DZwe21MlUdIuB3w7vqan8YUwlQ',
    appId: '1:775956968299:ios:db73c4733004c3a9e6122e',
    messagingSenderId: '775956968299',
    projectId: 'dalel-d73c2',
    storageBucket: 'dalel-d73c2.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKwBUSeUpSWPTsFQHL3pF5KG30J5--lp0',
    appId: '1:775956968299:web:4fbb26bb7ac8b80ce6122e',
    messagingSenderId: '775956968299',
    projectId: 'dalel-d73c2',
    authDomain: 'dalel-d73c2.firebaseapp.com',
    storageBucket: 'dalel-d73c2.firebasestorage.app',
    measurementId: 'G-E2FXCECTET',
  );
}
